on:
  push:
    branches:
      - main
  pull_request:

name: test-build-deploy
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: install dependencies
        run: npm install
      - name: build the page
        run: npm run build
